### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by mboronin** [lunixbochs/usercorn#229] opened 2017-04-23 15:39 UTC
sh -c "PATH='/mnt/c/Users/admin/Downloads/usercorn-master/usercorn-master/deps/go-x86_64-Linux/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' go get -u github.com/bnagy/gapstone github.com/chzyer/readline/runes github.com/keystone-engine/keystone/bindings/go/keystone github.com/lunixbochs/argjoy github.com/lunixbochs/fvbommel-util/sortorder github.com/lunixbochs/ghostrace/ghost/memio github.com/lunixbochs/ghostrace/ghost/sys/num github.com/lunixbochs/go-shellwords github.com/lunixbochs/readline github.com/lunixbochs/struc github.com/mattn/go-colorable github.com/mgutz/ansi github.com/unicorn-engine/unicorn/bindings/go/unicorn golang.org/x/crypto/ssh/terminal"
cd /mnt/c/Users/admin/Downloads/usercorn-master/usercorn-master/deps/gopath/src/github.com/chzyer/readline; git pull --ff-only
Already up-to-date.
package github.com/chzyer/readline/runes: read |0: interrupted system call
cd /mnt/c/Users/admin/Downloads/usercorn-master/usercorn-master/deps/gopath/src/github.com/keystone-engine/keystone; git submodule update --init --recursive
package github.com/keystone-engine/keystone/bindings/go/keystone: read |0: interrupted system call
cd /mnt/c/Users/admin/Downloads/usercorn-master/usercorn-master/deps/gopath/src/github.com/lunixbochs/fvbommel-util; git pull --ff-only
Already up-to-date.
package github.com/lunixbochs/fvbommel-util/sortorder: read |0: interrupted system call
cd /mnt/c/Users/admin/Downloads/usercorn-master/usercorn-master/deps/gopath/src/github.com/lunixbochs/go-shellwords; git pull --ff-only
Already up-to-date.
package github.com/lunixbochs/go-shellwords: read |0: interrupted system call
cd /mnt/c/Users/admin/Downloads/usercorn-master/usercorn-master/deps/gopath/src/github.com/lunixbochs/readline; git pull --ff-only
Already up-to-date.
package github.com/lunixbochs/readline: read |0: interrupted system call
cd /mnt/c/Users/admin/Downloads/usercorn-master/usercorn-master/deps/gopath/src/github.com/lunixbochs/struc; git pull --ff-only
Already up-to-date.
package github.com/lunixbochs/struc: read |0: interrupted system call
cd /mnt/c/Users/admin/Downloads/usercorn-master/usercorn-master/deps/gopath/src/github.com/mattn/go-colorable; git submodule update --init --recursive
package github.com/mattn/go-colorable: read |0: interrupted system call
cd /mnt/c/Users/admin/Downloads/usercorn-master/usercorn-master/deps/gopath/src/github.com/mgutz/ansi; git pull --ff-only
Already up-to-date.
package github.com/mgutz/ansi: read |0: interrupted system call
cd /mnt/c/Users/admin/Downloads/usercorn-master/usercorn-master/deps/gopath/src/github.com/unicorn-engine/unicorn; git submodule update --init --recursive
package github.com/unicorn-engine/unicorn/bindings/go/unicorn: read |0: interrupted system call
cd /mnt/c/Users/admin/Downloads/usercorn-master/usercorn-master/deps/gopath/src/golang.org/x/crypto; git submodule update --init --recursive
package golang.org/x/crypto/ssh/terminal: read |0: interrupted system call
make: *** [get] Error 1

Getting such output on make command. Windows 10 x64

**Comment by lunixbochs** [comment] 2017-04-23 16:04
This looks like a problem with WSL. The output looks nothing like this on Linux.

**Comment by lunixbochs** [comment] 2017-04-25 22:29
Duplicates https://github.com/Microsoft/BashOnWindows/issues/349

Have you updated to WSL 14905 / Creator's update? It should be fixed there.

**Comment by lunixbochs** [comment] 2017-04-27 02:19
Confirmed to work on Creator's Update. Just install it and Usercorn should work!

**Closed by lunixbochs** 2017-04-27 02:19 UTC
